/**
 * Curated, static allergen-category mapping for the `ingredients` table.
 *
 * This backs a hard-exclude allergy filter, so it is a manually-reviewed map,
 * not a runtime keyword/substring matcher — e.g. "Coconut Milk" is deliberately
 * absent from Dairy, and "Peanut Butter" is absent from Dairy despite the word
 * "Butter". Every entry below was decided on a case-by-case basis against the
 * exact ingredient name; most of the ~1000 rows in `ingredients` map to nothing
 * and are simply omitted.
 *
 * Known, deliberate gaps (see PR/commit description for the full list):
 * - Sulfites is intentionally thin: only wine/sherry, molasses, and dried
 *   apricots are tagged. Raisins, sultanas, other dried fruit, and vinegars
 *   are left untagged — sulfite treatment there is brand/process-dependent,
 *   not inferable from the ingredient name.
 * - Oats are NOT tagged Gluten (botanically gluten-free); the common
 *   cross-contamination risk during milling isn't something a name-based
 *   static map can represent.
 * - Dark/plain chocolate is NOT tagged Dairy (dairy-free by formulation);
 *   milk/white chocolate IS (dairy is definitional for those).
 * - Coconut is NOT tagged Tree Nuts, following common medical convention
 *   (US FDA labeling technically lists it under tree nuts).
 * - Black pepper / peppercorns are NOT tagged Nightshades — Piper nigrum is
 *   botanically unrelated to capsicum peppers.
 * - Liquid stocks (Beef Stock, Chicken Stock, etc.) are NOT tagged Gluten;
 *   stock CUBES/bouillon powder ARE, since wheat/barley filler is common in
 *   the dehydrated form specifically.
 */

export type AllergenType =
  | 'Shellfish'
  | 'Fish'
  | 'Gluten'
  | 'Dairy'
  | 'Peanuts'
  | 'Tree Nuts'
  | 'Soy'
  | 'Eggs'
  | 'Sesame'
  | 'Mustard'
  | 'Sulfites'
  | 'Nightshades'

export const ALLERGEN_TYPES: Record<string, AllergenType[]> = {
  // ---- Shellfish (crustaceans + mollusks) ----
  'King Prawns': ['Shellfish'],
  'Prawns': ['Shellfish'],
  'Raw King Prawns': ['Shellfish'],
  'Mussels': ['Shellfish'],
  'Squid': ['Shellfish'],
  'Baby Squid': ['Shellfish'],
  'Clams': ['Shellfish'],
  'Oysters': ['Shellfish'],
  'Oyster Sauce': ['Shellfish'],
  'Tiger Prawns': ['Shellfish'],
  'Shrimp': ['Shellfish'],
  'Raw tiger prawns': ['Shellfish'],
  'Raw Frozen Prawns': ['Shellfish'],
  'Conchs': ['Shellfish'],
  'Crab Meay': ['Shellfish'],
  'Lobster': ['Shellfish'],
  'Jumbo Shrimp': ['Shellfish'],
  'Dried Shrimp': ['Shellfish'],
  'Shrimp Paste': ['Shellfish'],
  'Shrimp Stock': ['Shellfish'],
  'Seafood stock': ['Shellfish', 'Fish'],
  'Frozen Seafood mix': ['Shellfish', 'Fish'],

  // ---- Fish ----
  'Salmon': ['Fish'],
  'Mackerel': ['Fish'],
  'Fish Sauce': ['Fish'],
  'Thai Fish Sauce': ['Fish'],
  'Tuna': ['Fish'],
  'White Fish': ['Fish'],
  'White Fish Fillets': ['Fish'],
  'Fish Stock': ['Fish'],
  'Monkfish': ['Fish'],
  'Pilchards': ['Fish'],
  'Cod': ['Fish'],
  'Salt Cod': ['Fish'],
  'Red Snapper': ['Fish'],
  'Anchovy Fillet': ['Fish'],
  'Smoked Salmon': ['Fish'],
  'Herring': ['Fish'],
  'Sardines': ['Fish'],
  'barramundi': ['Fish'],
  'Fish fillet': ['Fish'],
  'Hake': ['Fish'],
  'Trout': ['Fish'],
  'Rainbow Trout': ['Fish'],
  'Sea Bass': ['Fish'],
  'Sea Bass Fillets': ['Fish'],
  'Hot Smoked Flaked Salmon': ['Fish'],
  'Snapper Fish': ['Fish'],
  'Fish Seasoning': ['Fish'],
  'Codfish Bulljaw': ['Fish'],
  'Worcestershire Sauce': ['Fish', 'Gluten'],
  'Smoked Haddock': ['Fish'],
  'Haddock': ['Fish'],
  'Prahok': ['Fish'],

  // ---- Gluten (wheat / barley / rye) ----
  'Bread': ['Gluten'],
  'Breadcrumbs': ['Gluten'],
  'Bowtie Pasta': ['Gluten'],
  'Farfalle': ['Gluten'],
  'Flour': ['Gluten'],
  'Flour Tortilla': ['Gluten'],
  'Tortillas': ['Gluten'],
  'Lasagne Sheets': ['Gluten'],
  'Macaroni': ['Gluten'],
  'Pappardelle Pasta': ['Gluten'],
  'Paccheri Pasta': ['Gluten'],
  'Linguine Pasta': ['Gluten'],
  'Vermicelli Pasta': ['Gluten'],
  'Penne Rigate': ['Gluten'],
  'Penne Pasta': ['Gluten'],
  'Rigatoni': ['Gluten'],
  'Tagliatelle': ['Gluten'],
  'Fettuccine': ['Gluten'],
  'Spaghetti': ['Gluten'],
  'Noodles': ['Gluten'],
  'Naan Bread': ['Gluten'],
  'Baguette': ['Gluten'],
  'Ciabatta': ['Gluten'],
  'Pita Bread': ['Gluten'],
  'Bread Rolls': ['Gluten'],
  'Bun': ['Gluten'],
  'Buns': ['Gluten'],
  'Potatoe Buns': ['Gluten'],
  'Sesame Seed Burger Buns': ['Gluten', 'Sesame'],
  'English Muffins': ['Gluten'],
  'Muffins': ['Gluten'],
  'Digestive Biscuits': ['Gluten'],
  'Pretzels': ['Gluten'],
  'Puff Pastry': ['Gluten'],
  'Shortcrust Pastry': ['Gluten'],
  'Ready rolled shortcrust pastry': ['Gluten'],
  'Filo Pastry': ['Gluten'],
  'Phyllo Dough': ['Gluten'],
  'Couscous': ['Gluten'],
  'Bulgur Wheat': ['Gluten'],
  'Semolina': ['Gluten'],
  'Semolina Flour': ['Gluten'],
  'Beer': ['Gluten'],
  'Dark Beer': ['Gluten'],
  'Stout': ['Gluten'],
  'Soy Sauce': ['Gluten', 'Soy'],
  'Dark Soy Sauce': ['Gluten', 'Soy'],
  'Hoisin Sauce': ['Gluten', 'Soy'],
  'Malt Vinegar': ['Gluten'],
  'Chicken Stock Cube': ['Gluten'],
  'Vegetable Stock Cube': ['Gluten'],
  'Beef Stock Cubes': ['Gluten'],
  'Bouillon Cubes': ['Gluten'],
  'Chicken Bouillon Powder': ['Gluten'],
  'Egg Roll Wrappers': ['Gluten'],
  'Egg Rolls': ['Gluten'],
  'Wonton Skin': ['Gluten'],
  'Egg Noodles': ['Gluten', 'Eggs'],
  'Knafeh': ['Gluten'],
  'Graham Cracker Crumbs': ['Gluten'],
  'Grape Nut Cereal': ['Gluten'],
  'Rice Krispies': ['Gluten'],
  'Mixed Grain': ['Gluten'],
  'Freekeh': ['Gluten'],
  'Toast': ['Gluten'],
  'Stale bread': ['Gluten'],
  'White bread': ['Gluten'],
  'Crusty Bread': ['Gluten'],
  'Cuban Bread': ['Gluten'],
  'Christmas Pudding': ['Gluten'],
  'Black Pudding': ['Gluten'],
  'Mars Bar': ['Gluten', 'Dairy'],
  'Oreo Cream Biscuits': ['Gluten'],
  'Maria Cookies': ['Gluten'],
  'Strong Wholemeal Flour': ['Gluten'],
  'Tempura Flour': ['Gluten'],
  'White Flour': ['Gluten'],
  'Bread Flour': ['Gluten'],
  'Strong white bread flour': ['Gluten'],
  'Self-raising Flour': ['Gluten'],
  'Plain Flour': ['Gluten'],
  'All purpose flour': ['Gluten'],
  'Wheat Flour': ['Gluten'],
  'Whole Wheat': ['Gluten'],
  'Wholegrain Bread': ['Gluten'],
  'White Bread Mix': ['Gluten'],
  'Rye': ['Gluten'],
  'Rye Bread': ['Gluten'],
  'Rye Flour': ['Gluten'],
  'Rye Grain': ['Gluten'],
  'Farine': ['Gluten'],
  'Sevaiiya': ['Gluten'],
  'Beef Gravy': ['Gluten'],
  'Pre-fried Tequeños': ['Gluten', 'Dairy'],

  // ---- Dairy ----
  'Butter': ['Dairy'],
  'Chilled Butter': ['Dairy'],
  'Salted Butter': ['Dairy'],
  'Unsalted Butter': ['Dairy'],
  'Melted Butter': ['Dairy'],
  'Ghee': ['Dairy'],
  'Cheese': ['Dairy'],
  'Cheddar Cheese': ['Dairy'],
  'Mature Cheddar': ['Dairy'],
  'Cheese Curds': ['Dairy'],
  'Colby Jack Cheese': ['Dairy'],
  'Cubed Feta Cheese': ['Dairy'],
  'Feta': ['Dairy'],
  'Gouda Cheese': ['Dairy'],
  'Gruyère': ['Dairy'],
  'Monterey Jack Cheese': ['Dairy'],
  'Shredded Monterey Jack Cheese': ['Dairy'],
  'Mozzarella Balls': ['Dairy'],
  'Mozzarella': ['Dairy'],
  'Parmesan': ['Dairy'],
  'Parmesan Cheese': ['Dairy'],
  'Parmigiano-reggiano': ['Dairy'],
  'Pecorino': ['Dairy'],
  'Shredded Mexican Cheese': ['Dairy'],
  'Stilton Cheese': ['Dairy'],
  'Mascarpone': ['Dairy'],
  'Ricotta': ['Dairy'],
  'Cream Cheese': ['Dairy'],
  'Goats Cheese': ['Dairy'],
  'Brie': ['Dairy'],
  'Cottage Cheese': ['Dairy'],
  'manchego': ['Dairy'],
  'Bryndza cheese': ['Dairy'],
  'Emmentaler Cheese': ['Dairy'],
  'Swiss Cheese': ['Dairy'],
  'Farmers Cheese': ['Dairy'],
  'Queso Fresco': ['Dairy'],
  'Panquehue Cheese': ['Dairy'],
  'västerbottensost cheese': ['Dairy'],
  'Cheese Slices': ['Dairy'],
  'Liquid Cheese': ['Dairy'],
  'Corn Arepa Filled With Mozarella Cheese': ['Dairy'],
  'Milk': ['Dairy'],
  'Whole Milk': ['Dairy'],
  'Semi-skimmed Milk': ['Dairy'],
  'Condensed Milk': ['Dairy'],
  'Sweetened Condensed Milk': ['Dairy'],
  'Evaporated Milk': ['Dairy'],
  'Sour Milk': ['Dairy'],
  'Buttermilk': ['Dairy'],
  'Cream': ['Dairy'],
  'Double Cream': ['Dairy'],
  'Heavy Cream': ['Dairy'],
  'Single Cream': ['Dairy'],
  'Whipping Cream': ['Dairy'],
  'Clotted Cream': ['Dairy'],
  'Sour Cream': ['Dairy'],
  'Full fat sour cream': ['Dairy'],
  'Soured cream and chive dip': ['Dairy'],
  'Creme Fraiche': ['Dairy'],
  'Fromage Frais': ['Dairy'],
  'Yogurt': ['Dairy'],
  'Greek Yogurt': ['Dairy'],
  'Full Fat Yogurt': ['Dairy'],
  'Natural Yoghurt': ['Dairy'],
  'Strained Yoghurt': ['Dairy'],
  'Ice Cream': ['Dairy'],
  'Custard': ['Dairy', 'Eggs'],
  'Vanilla Custard': ['Dairy', 'Eggs'],
  'Malai': ['Dairy'],
  'Paneer': ['Dairy'],
  'Sweet Quark': ['Dairy'],
  'Milk Chocolate': ['Dairy'],
  'White Chocolate': ['Dairy'],
  'White Chocolate Chips': ['Dairy'],
  'Dulce de leche': ['Dairy'],
  'Caramel': ['Dairy'],
  'Caramel Sauce': ['Dairy'],
  'Caramelized Sugar Sauce': ['Dairy'],
  'Toffee Popcorn': ['Dairy'],
  'Nutella': ['Dairy', 'Tree Nuts'],

  // ---- Peanuts ----
  'Peanut Butter': ['Peanuts'],
  'Peanut Oil': ['Peanuts'],
  'Peanuts': ['Peanuts'],
  'Unsalted Peanuts': ['Peanuts'],
  'Roasted Peanut': ['Peanuts'],
  'Peanut Cookies': ['Peanuts', 'Gluten'],
  'Peanut Brittle': ['Peanuts'],

  // ---- Tree Nuts ----
  'Cashew Nuts': ['Tree Nuts'],
  'Cashews': ['Tree Nuts'],
  'Flaked Almonds': ['Tree Nuts'],
  'Ground Almonds': ['Tree Nuts'],
  'Almonds': ['Tree Nuts'],
  'Almond Milk': ['Tree Nuts'],
  'Almond Extract': ['Tree Nuts'],
  'Almond Flour': ['Tree Nuts'],
  'Almond Paste': ['Tree Nuts'],
  'Almond Essence': ['Tree Nuts'],
  'Marzipan': ['Tree Nuts'],
  'Pine Nuts': ['Tree Nuts'],
  'Walnuts': ['Tree Nuts'],
  'Ground Walnuts': ['Tree Nuts'],
  'Pecan Nuts': ['Tree Nuts'],
  'Chestnuts': ['Tree Nuts'],
  'Cooked Chestnut': ['Tree Nuts'],
  'Hazlenuts': ['Tree Nuts'],
  'Shelled Hazelnuts': ['Tree Nuts'],
  'Pistachio': ['Tree Nuts'],
  'Unsalted Pistachio': ['Tree Nuts'],
  'Ground Pistachios': ['Tree Nuts'],
  'Pistachio Paste': ['Tree Nuts'],
  'Nougatine': ['Tree Nuts'],

  // ---- Soy ----
  'Soya Milk': ['Soy'],
  'Soya Bean': ['Soy'],
  'Tofu': ['Soy'],
  'Marinated Tofu': ['Soy'],
  'Silken Tofu': ['Soy'],
  'Tempeh': ['Soy'],
  'Doubanjiang': ['Soy', 'Nightshades'],
  'Fermented Black Beans': ['Soy'],
  'Chilli Bean Paste': ['Soy', 'Nightshades'],
  'Gochujang': ['Soy', 'Nightshades'],

  // ---- Eggs ----
  'Eggs': ['Eggs'],
  'Egg': ['Eggs'],
  'Egg White': ['Eggs'],
  'Egg Yolks': ['Eggs'],
  'Free-range Egg, Beaten': ['Eggs'],
  'Free-range Eggs, Beaten': ['Eggs'],
  'Egg Wash': ['Eggs'],
  'Meringue Nests': ['Eggs'],
  'Mayonnaise': ['Eggs'],
  'Smoky Aïoli': ['Eggs'],

  // ---- Sesame ----
  'Sesame Seed': ['Sesame'],
  'Sesame Seed Oil': ['Sesame'],
  'Tahini': ['Sesame'],
  'Tahini Paste': ['Sesame'],
  'Chinese Sesame Sauce': ['Sesame'],
  'Hummus': ['Sesame'],

  // ---- Mustard ----
  'Mustard': ['Mustard'],
  'Mustard Powder': ['Mustard'],
  'Mustard Seeds': ['Mustard'],
  'English Mustard': ['Mustard'],
  'Dijon Mustard': ['Mustard'],
  'Wholegrain Mustard': ['Mustard'],
  'Ground Mustard': ['Mustard'],
  'Panch Poran': ['Mustard'],
  'Salsa Lizano': ['Mustard'],

  // ---- Sulfites (intentionally thin — see file header) ----
  'Dry White Wine': ['Sulfites'],
  'Red Wine': ['Sulfites'],
  'White Wine': ['Sulfites'],
  'Sherry': ['Sulfites'],
  'Dry sherry': ['Sulfites'],
  'Sweet Sherry': ['Sulfites'],
  'Molasses': ['Sulfites'],
  'Dried Apricots': ['Sulfites'],

  // ---- Nightshades (tomato / potato / pepper-capsicum / eggplant) ----
  'Aubergine': ['Nightshades'],
  'Baby Aubergine': ['Nightshades'],
  'Egg Plants': ['Nightshades'],
  'Baby Plum Tomatoes': ['Nightshades'],
  'Canned Tomatoes': ['Nightshades'],
  'Cherry Tomatoes': ['Nightshades'],
  'Chopped Tomatoes': ['Nightshades'],
  'Diced Tomatoes': ['Nightshades'],
  'Grape Tomatoes': ['Nightshades'],
  'Plum Tomatoes': ['Nightshades'],
  'Tomatoes': ['Nightshades'],
  'Tomato': ['Nightshades'],
  'Tinned Tomatos': ['Nightshades'],
  'Vine Tomatoes': ['Nightshades'],
  'Sun-Dried Tomatoes': ['Nightshades'],
  'Beef tomatoes': ['Nightshades'],
  'Tomato Ketchup': ['Nightshades'],
  'Tomato Puree': ['Nightshades'],
  'Tomato Sauce': ['Nightshades'],
  'Passata': ['Nightshades'],
  'Enchilada Sauce': ['Nightshades'],
  'Green Salsa': ['Nightshades'],
  'Salsa': ['Nightshades'],
  'Pico De Gallo Sauce': ['Nightshades'],
  'Barbeque Sauce': ['Nightshades'],
  'Cayenne Pepper': ['Nightshades'],
  'Chili Powder': ['Nightshades'],
  'Chilli Powder': ['Nightshades'],
  'Red Chilli Powder': ['Nightshades'],
  'Hot Chilli Powder': ['Nightshades'],
  'Chilli': ['Nightshades'],
  'Green Chilli': ['Nightshades'],
  'Red Chilli': ['Nightshades'],
  'Red Chilli Flakes': ['Nightshades'],
  'Red Pepper Flakes': ['Nightshades'],
  'Chilli Flakes': ['Nightshades'],
  'Jalapeno': ['Nightshades'],
  'Scotch Bonnet': ['Nightshades'],
  'Ancho Chillies': ['Nightshades'],
  'Dried Red Chillies': ['Nightshades'],
  'Dried Chillies': ['Nightshades'],
  'Birds-eye Chillies': ['Nightshades'],
  'Thai Chilli Jam': ['Nightshades'],
  'Chilli Sauce': ['Nightshades'],
  'sweet chilli sauce': ['Nightshades'],
  'Hotsauce': ['Nightshades'],
  'Tabasco Sauce': ['Nightshades'],
  'Tobasco Sauce': ['Nightshades'],
  'Sriracha': ['Nightshades'],
  'Red Pepper': ['Nightshades'],
  'Yellow Pepper': ['Nightshades'],
  'Green Pepper': ['Nightshades'],
  'Romano Pepper': ['Nightshades'],
  'Red Pepper Paste': ['Nightshades'],
  'Sweet Peppadew Peppers': ['Nightshades'],
  'Roasted pepper': ['Nightshades'],
  'Mixed peppers': ['Nightshades'],
  'Padron peppers': ['Nightshades'],
  'Sweet Red Peppers': ['Nightshades'],
  'Banana Pepper': ['Nightshades'],
  'Habanero Pepper': ['Nightshades'],
  'Red Pepper Sauce': ['Nightshades'],
  'Pimento Stuffed Olives': ['Nightshades'],
  'Pul Biber': ['Nightshades'],
  'Paprika': ['Nightshades'],
  'Smoked Paprika': ['Nightshades'],
  'Smoky Paprika': ['Nightshades'],
  'sweet smoked paprika': ['Nightshades'],
  'Hot smoked paprika': ['Nightshades'],
  'Potatoes': ['Nightshades'],
  'Potato Starch': ['Nightshades'],
  'Charlotte Potatoes': ['Nightshades'],
  'Floury Potatoes': ['Nightshades'],
  'Small Potatoes': ['Nightshades'],
  'Baby New Potatoes': ['Nightshades'],
  'Jersey Royal Potatoes': ['Nightshades'],
  'Red Potatoes': ['Nightshades'],
  'Yukon Gold Potatoes': ['Nightshades'],
  'New Potatoes': ['Nightshades'],
  'Russet Potato': ['Nightshades'],
  'Fries': ['Nightshades'],
  'Harissa Spice': ['Nightshades'],
  'Cajun': ['Nightshades'],
  'Jerk': ['Nightshades'],
  'Fajita Seasoning': ['Nightshades'],
  'Curry Powder': ['Nightshades'],
  'Jamaican Curry Powder': ['Nightshades'],
  'Madras Paste': ['Nightshades'],
  'Massaman Curry Paste': ['Nightshades'],
  'Thai Green Curry Paste': ['Nightshades'],
  'Thai Red Curry Paste': ['Nightshades'],
  'Panang Curry Paste': ['Nightshades'],
  'Red Curry Paste': ['Nightshades'],
  'Biryani Masala': ['Nightshades'],
}
