-- Append-only log of every recipe assigned to a plan day. `meal_plan_entries`
-- is upserted per weekday and keeps no history, so Auto Plan (issue #3) needs
-- this to know what's been cooked recently or never at all.
-- See ARCHITECTURE.md § "Auto plan algorithm".

create table recipe_plan_history (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  recipe_id    text not null references recipes(id) on delete cascade,
  planned_date date not null default (now()::date),
  created_at   timestamptz not null default now()
);

create index recipe_plan_history_user_recipe_idx
  on recipe_plan_history (user_id, recipe_id, planned_date desc);

alter table recipe_plan_history enable row level security;

create policy recipe_plan_history_read on recipe_plan_history
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy recipe_plan_history_insert on recipe_plan_history
  for insert to authenticated
  with check (user_id = (select auth.uid()));
